version: 0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
before_build:
- set PATH="C:\Program Files (x86)\MSBuild\14.0\Bin";%PATH%
build:
  verbosity: minimal
  publish_nuget: true
  publish_nuget_symbols: true

test_script:
- ps: >-
    $source = "https://s3.amazonaws.com/influxdb/influxdb-nightly_windows_amd64.zip"

    $destination = "$env:Temp\influxdb-nightly_windows_amd64.zip"

    Invoke-WebRequest $source -OutFile $destination

    $x = 7z x $destination -o"$env:Temp\influxdb"

    Start-Process -FilePath "$env:Temp\influxdb\influxd.exe"

    pwd

    vstest.console /logger:Appveyor ".\Influxer.Test\bin\Debug\InfluxerTest.orderedtest"