version: 0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
before_build:
- cmd: nuget restore -verbosity detailed
- set PATH="C:\Program Files (x86)\MSBuild\14.0\Bin";%PATH%
build:
  verbosity: minimal
artifacts:
- path: Influxer\bin\debug
  name: InfluxerDebug
before_test:
- ps: Influxer.Test\TestSetup.ps1