version: 0.{build}
image: Visual Studio 2017
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
before_build:
- nuget restore
- dotnet restore
platform: Any CPU
configuration: Release
build:
  verbosity: minimal
artifacts:
- path: Influxer\bin\$(configuration)
  name: InfluxerLatest
before_test:
- ps: Influxer.Test\TestSetup.ps1